### ISSUE TITLE
TK issue in Gaussian fit

### ISSUE THREAD

**Issue by jmcclena** [maxcurie1996/SLiM#2]
Running `000GUI_SLiM_mode_finder.py`, I get the following error:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/mcclenaghan/opt/anaconda3/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "000GUI_SLiM_mode_finder.py", line 516, in <lambda>
    command=lambda: Load_data(profile_name,\
  File "000GUI_SLiM_mode_finder.py", line 395, in Load_data
    mean_rho,xstar=mode_finder_obj.omega_gaussian_fit_GUI(root,\
  File "/Users/mcclenaghan/programming/SLiM/SLiM_obj.py", line 606, in omega_gaussian_fit_GUI
    amplitude,mean,stddev=gaussian_fit_GUI(root,x,data)
  File "./Tools/Gaussian_fit.py", line 36, in gaussian_fit_GUI
    top.iconbitmap('./SLiM.ico')
  File "/Users/mcclenaghan/opt/anaconda3/lib/python3.8/tkinter/__init__.py", line 2080, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "./SLiM.ico" not defined
```

**Comment by maxtcurie** [comment]
icon loading problem has been resolved by try except

**Comment by jmcclena** [comment]
thanks!
